# Configuração do Prometheus para JP Marcenaria Digital
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'jp-marcenaria-monitor'
    environment: 'production'

# Configuração de alertas
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Regras de alerta
rule_files:
  - "alert_rules.yml"

# Configuração de scraping
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (métricas do sistema)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Aplicação Frontend (se tiver métricas expostas)
  - job_name: 'jp-marcenaria-frontend'
    static_configs:
      - targets: ['app:5173']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Supabase/PostgreSQL (se configurado)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 60s

  # Blackbox Exporter para monitoramento de endpoints
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://jpmarcenaria.com
        - https://jpmarcenaria.com/servicos
        - https://jpmarcenaria.com/portfolio
        - https://jpmarcenaria.com/contato
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Monitoramento de SSL/TLS
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - jpmarcenaria.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Monitoramento de DNS
  - job_name: 'blackbox-dns'
    metrics_path: /probe
    params:
      module: [dns]
    static_configs:
      - targets:
        - jpmarcenaria.com
        - www.jpmarcenaria.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Métricas customizadas da aplicação via pushgateway
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 15s
    honor_labels: true

# Configuração de armazenamento
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Configuração de logging
log_level: info
log_format: json